apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress-without-pvc-route
  namespace: sandbox
spec:
  host: <YOUR_APP_NAME>.apps.<YOUR_CLUSTER_NAME>.<BASE_DOMAIN>
  path: /
  to:
    kind: Service
    name: wordpress-without-pvc
  port:
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-without-pvc
  namespace: sandbox
  labels:
    app: wordpress-without-pvc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wordpress-without-pvc
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-without-pvc
  namespace: sandbox
  labels:
    app: wordpress-without-pvc
spec:
  selector:
    matchLabels:
      app: wordpress-without-pvc
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-without-pvc
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql-without-pvc
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
